def prop_list():
    return ['banded',
    'bidiagonal',
    'binary',
    'block Toeplitz',
    'built-in',
    'circulant',
    'complex',
    'correlation',
    'defective',
    'diagonally dominant',
    'eigenvalues',
    'fixed size',
    'hankel',
    'hermitian',
    'hessenberg',
    'idempotent',
    'indefinite',
    'ill conditioned',
    'infinitely divisible',
    'integer',
    'inverse',
    'involutory',
    'M-matrix',
    'nilpotent',
    'nonnegative',
    'normal',
    'orthogonal',
    'parameter-dependent',
    'permutation',
    'positive',
    'positive definite',
    'pseudo-orthogonal',
    'random',
    'rank deficient',
    'real',
    'rectangular',
    'scalable',
    'singular values',
    'skew-hermitian',
    'skew-symmetric',
    'sparse',
    'square',
    'stochastic',
    'symmetric',
    'toeplitz',
    'totally nonnegative',
    'totally positive',
    'triangular',
    'tridiagonal',
    'unimodular',
    'unitary'
    ]
